kind: Deployment
apiVersion: apps/v1
metadata:
  name: fuse710-karaf-camel-log
  namespace: test-argo
  labels:
    app: fuse710-karaf-camel-log
    app.kubernetes.io/component: fuse710-karaf-camel-log
    app.kubernetes.io/instance: fuse710-karaf-camel-log
    app.kubernetes.io/name: fuse710-karaf-camel-log
    app.kubernetes.io/part-of: fuse710-karaf-camel-log-app
    app.openshift.io/runtime: fuse710-karaf-camel-log
    app.openshift.io/runtime-namespace: karaf-log
    app.openshift.io/runtime-version: latest    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fuse710-karaf-camel-log
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fuse710-karaf-camel-log
        deploymentconfig: fuse710-karaf-camel-log
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: fuse710-karaf-camel-log
          image: >-
            image-registry.openshift-image-registry.svc:5000/karaf-log/fuse710-karaf-camel-log@sha256:d4b847e551e09af297853cef000e85a868ba450dfcbbfec8b8f26124d95827b2
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
 