kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: fuse710-karaf-camel-log
  namespace: test-argo
  uid: d784fb45-412c-47db-91db-6a9d59016713
  resourceVersion: '187468'
  generation: 3
  creationTimestamp: '2022-02-05T20:31:08Z'
  labels:
    app: fuse710-karaf-camel-log
    group: org.example.fis
    provider: jkube
    version: 1.0-SNAPSHOT
  managedFields:
    - manager: okhttp
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-05T20:31:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:group': {}
            'f:provider': {}
            'f:version': {}
        'f:spec':
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            .: {}
            'f:app': {}
            'f:group': {}
            'f:provider': {}
          'f:strategy':
            'f:activeDeadlineSeconds': {}
            'f:rollingParams':
              .: {}
              'f:intervalSeconds': {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
              'f:timeoutSeconds': {}
              'f:updatePeriodSeconds': {}
            'f:type': {}
          'f:template':
            .: {}
            'f:metadata':
              .: {}
              'f:creationTimestamp': {}
              'f:labels':
                'f:version': {}
                'f:provider': {}
                'f:group': {}
                'f:app': {}
                .: {}
                'f:rht.prod_name': {}
                'f:rht.comp': {}
                'f:rht.comp_ver': {}
                'f:com.company': {}
                'f:rht.prod_ver': {}
            'f:spec':
              .: {}
              'f:containers':
                .: {}
                'k:{"name":"karaf"}':
                  'f:image': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:env':
                    .: {}
                    'k:{"name":"KUBERNETES_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef': {}
                    'k:{"name":"QUICKSTART_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:readinessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:securityContext':
                    .: {}
                    'f:privileged': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8181,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":8778,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-05T20:31:09Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:triggers': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps.openshift.io/v1
      time: '2022-02-05T20:31:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:updatedReplicas': {}
          'f:readyReplicas': {}
          'f:conditions':
            'k:{"type":"Available"}':
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:status': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:details':
            .: {}
            'f:causes': {}
            'f:message': {}
          'f:replicas': {}
          'f:availableReplicas': {}
          'f:observedGeneration': {}
          'f:unavailableReplicas': {}
          'f:latestVersion': {}
      subresource: status
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 3600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - karaf
        from:
          kind: ImageStreamTag
          namespace: karaf-log
          name: 'fuse710-karaf-camel-log:latest'
        lastTriggeredImage: >-
          image-registry.openshift-image-registry.svc:5000/karaf-log/fuse710-karaf-camel-log@sha256:4afac1d9c3de56e1be72f4e9f88db213da52bd4d209ebef53d108bfef0c8c1b2
  replicas: 1
  revisionHistoryLimit: 2
  test: false
  selector:
    app: fuse710-karaf-camel-log
    group: org.example.fis
    provider: jkube
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fuse710-karaf-camel-log
        rht.comp_ver: 7.10.0.fuse-sb2-7_10_0-00014-redhat-00001
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: '7.10'
        com.company: Red_Hat
        provider: jkube
        version: 1.0-SNAPSHOT
        rht.comp: karaf-camel-log
        group: org.example.fis
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /readiness-check
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: karaf
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: QUICKSTART_NAME
              value: karaf-camel-log
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          securityContext:
            privileged: false
          ports:
            - name: intermapper
              containerPort: 8181
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/karaf-log/fuse710-karaf-camel-log@sha256:4afac1d9c3de56e1be72f4e9f88db213da52bd4d209ebef53d108bfef0c8c1b2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 3
  details:
    message: config change
    causes:
      - type: ConfigChange
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 1
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2022-02-05T20:31:45Z'
      lastTransitionTime: '2022-02-05T20:31:45Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2022-02-05T20:31:46Z'
      lastTransitionTime: '2022-02-05T20:31:46Z'
      reason: NewReplicationControllerAvailable
      message: >-
        replication controller "fuse710-karaf-camel-log-1" successfully rolled
        out
  replicas: 1
  readyReplicas: 1
